# Group HOGE

# HOGEAPI [GET /api/hoge/{key}]

+ Relation: self

+ Parameters

    + key (string, required) ... キー

+ Response 200 (application/json; charset=utf8)
    + Attributes

    + Headers

    + Body

            {
              error: {},
              contents: [
                {
                  name: 'HOGE',
                },
                {
                  name: 'FUGA',
                }
              ]
            }
