# Case 2 [POST /case/02]
​
## have a some copy

this example have a some copy.

+ Request basic (application/json)

    + Body
​
            {
              payload: {
                message: "case"
              }
            }


+ Response 200 (application/json)

    + Body

            {
              message: "case"
            }
